### PR TITLE
build(deps-dev): replace eslint-plugin-node with eslint-plugin-n

### PR DESCRIPTION
**Pull request by Fdawgs**
`eslint-plugin-node` is no longer maintained.
Main repo migrated a while back:

https://github.com/fastify/fastify/blob/67bee117a7c5c6dad503f656204e49cf329a37af/package.json#L144

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Does it work without touching the eslint config?

**Comment by Fdawgs** [comment]
> Does it work without touching the eslint config?

Ah fudge, missed that.

**Comment by Uzlopak** [comment]
I am just curios why it is not erroring when linting. Maybe the plugin gets not required at all?

**Comment by climba03003** [comment]
> Maybe the plugin gets not required at all?

ESLint always try his best to lint even if their are something wrong with the setting.

Replace to `eslint-plugin-n` require the bump all the corresponding packages which includes `eslint` and `eslint-config-standard`.
They are not independent from each another.

**Comment by Fdawgs** [comment]
> Does it work without touching the eslint config?

Sorted in https://github.com/fastify/busboy/pull/98/commits/603b708f966251ea193d7179a40937228e06171a

**Review by Uzlopak — APPROVED** [review]

**Pull request merged**
