### PR TITLE
v2.1.1

### PR DESCRIPTION
**Pull request by gurgunday**

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]

**Review by Eomm — COMMENTED** [review]
we push the new version on master when we push a new release. Is there something not sync?

**Comment by gurgunday** [comment]
@Eomm I know, and would love to do it like that, but it says `main` is a protected branch now

I was going to ask if this is a new thing actually - if not, could you disable that rule?

**Comment by Eomm** [comment]
@gurgunday Fixed

Try again 👍🏼

**Comment by gurgunday** [comment]
@Eomm still seeing the following:

Screenshot 2024-02-28 at 15 19 32

**Comment by Eomm** [comment]
PTAL

Anyway, you are not using releasify 😭

**Comment by gurgunday** [comment]
I swear it was on my mind to switch to it 🤣

Will use that if I can now 🙏

**Pull request closed without merging**
