### PR TITLE
ci!: migrate to reusable workflow

### PR DESCRIPTION
**Pull request by Fdawgs**
BREAKING CHANGE: drops support for node 10, 12, and 17; adds support for node 18

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Hi fdawgs, why not use the reusable workflow plugin-ci of fastify/workflows?

**Comment by Fdawgs** [comment]
> Hi fdawgs, why not use the reusable workflow plugin-ci of fastify/workflows?

This repo tests on ubuntu and macos but not windows, which the reusable workflow does.
Can migrate to that if you're happy to also test on windows?

**Comment by Uzlopak** [comment]
The code is platform independent. So we can additionally test for windows and dropping the tests for node 10 and 12. Totally fine.

We could then close #65

**Comment by Fdawgs** [comment]
Updated to use shared workflow. The "required" job will need to be updated to use the new names I think.

**Review by Uzlopak — APPROVED** [review]

**Comment by Fdawgs** [comment]
Thanks @Uzlopak, ended up accidentally deleting the fork whilst cleaning up my repos 🙃

**Pull request merged**
