### PR TITLE
fix empty part bug

### PR DESCRIPTION
**Pull request by Uzlopak**
This is not mergable. It adds a unit test to test if the bug still exists.

If I apply the patch from 
https://github.com/mscdex/dicer/issues/23

then it still throws an error. I would have actually expected gracefully handling part and skipping it. 

We have to discuss, what the best approach is to solve this issue. 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by kibertoad** [comment]
@ruur Maybe you would like to participate in discussion?

**Comment by ruur** [comment]
@kibertoad I think this is a dicer bug, not busboy, which can only be corrected in dicer.

**Comment by kibertoad** [comment]
@ruur We inlined dicer into fastify-busboy, so we can try fixing it now.

**Comment by Uzlopak** [comment]
created a new PR #55 
please participate there @ruur  @kibertoad

**Pull request closed without merging**
