### PR TITLE
benchmarks

### PR DESCRIPTION
**Pull request by Uzlopak**
I had this in my git stash. I could not get multiparty to work.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
with 1mb:
parted throws an error, for some reason
```
node ./bench/benchmark.js 
busboy fastify x 1,591 ops/sec ±2.37% (71 runs sampled)
busboy legacy x 1,050 ops/sec ±2.83% (74 runs sampled)
formidable x 2,217 ops/sec ±1.32% (86 runs sampled)
multipartser x 1,350 ops/sec ±12.32% (55 runs sampled)
Fastest is formidable
```

with 10 mb
```
node ./bench/benchmark.js 
busboy fastify x 797 ops/sec ±2.46% (76 runs sampled)
busboy legacy x 292 ops/sec ±1.13% (81 runs sampled)
parted x 1,471 ops/sec ±3.71% (77 runs sampled)
formidable x 336 ops/sec ±2.94% (77 runs sampled)
multipartser x 165 ops/sec ±1.23% (78 runs sampled)
Fastest is parted
```

with 100mb
```
node ./bench/benchmark.js 
busboy fastify x 96.03 ops/sec ±0.70% (77 runs sampled)
busboy legacy x 33.93 ops/sec ±2.45% (60 runs sampled)
parted x 85.27 ops/sec ±0.65% (73 runs sampled)
formidable x 47.63 ops/sec ±0.35% (62 runs sampled)
multipartser x 16.49 ops/sec ±0.40% (46 runs sampled)
Fastest is busboy fastify
```

**Comment by Uzlopak** [comment]
I think that the benchmark is probable not correct. When I reduce the payload to 0.5 mb, Node crashes. So I guess, there is a memory leak, created by busboy?
If I do 0.5 Mb benchmark with the old files, i dont get a node crash. So there is something wrong with the benchmark.js variant. 
I guess you have to do the tests deferred and not sync?

Would be great if you could have a look at it @kibertoad

**Comment by kibertoad** [comment]
Sure, I'll take a look. I wrote https://github.com/kibertoad/photofinish a while ago, will try using it to verify if there is memory leak in benchmark library itself or our implementation of the test.

**Comment by Uzlopak** [comment]
@kibertoad 
can i throw away this PR?

**Comment by kibertoad** [comment]
I think so.

**Pull request closed without merging**
