### PR TITLE
handle unpipeing, cancelling or destroying of busboy accordingly

### PR DESCRIPTION
**Pull request by Uzlopak**
Should fix https://github.com/fastify/fastify-multipart/issues/315

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by kibertoad** [comment]
Yes, it does look like the right solution. Can we cover it with tests though?

**Comment by Uzlopak** [comment]
tbh I have no idea how to simulate an aborted upload.

**Comment by Uzlopak** [comment]
Do you have any idea how to implement it?

**Comment by mccare** [comment]
Looking through the tests, I would do it similar to the multipart-pause (https://github.com/fastify/busboy/blob/6d8f8741cd5a9787fe7c4d1f1fb57bd165ad6c66/test/multipart-stream-pause.spec.js#L76) 

Btw, would you need to clear the event listener on busboy after the file has been succesfully processed?

**Comment by mcollina** [comment]
Any update on this one?

**Comment by kibertoad** [comment]
I can try adding the test in a day or two if @Uzlopak doesn't do it first.

**Comment by Uzlopak** [comment]
If you call destroy again, it is handled as a no-op. https://nodejs.org/api/stream.html#writabledestroyerror
So it is no problem to destroy it again. 

Regarding the removal of the listener: Does it really matter? It either fails totally or it succeeds together. We dont pass an error object to destroy, so destroying the busboy-stream after we processed everything should not result in any additional errors. So if the FileStream got piped and processed it can be savely destroyed, imho.

**Comment by Uzlopak** [comment]
So what is now with this PR?

**Review by kibertoad — APPROVED** [review]

**Pull request merged**
