### PR TITLE
Integrate SearchStream

### PR DESCRIPTION
**Pull request by Uzlopak**
This PR integrates Searchstream package into busboy.

It also uses now Buffer.from and Buffer.allocate instead of the old constructor notation.

I also wrote unit tests for it. Seems I missed two branches.

I think the real bottle neck is this piece of code. 

The original searchstream was made for node 0.8.0. So it does not use anything which could improve the performance. The hottest parts are actually these lines

Screenshot from 2021-11-29 10-47-52

We need either optimize searchstream or replace it with a modern solution. 

By simply replacing the jsmemcmp function with Buffer.compare (which didnt exist for node 0.8.0 the benchmark looks like this:

```
> @fastify/busboy@1.0.0 bench:dicer
> node deps/dicer/bench/dicer-bench-multipart-parser.js

2500.00 mb/sec
2272.73 mb/sec
2222.22 mb/sec
3846.15 mb/sec
4000.00 mb/sec
4000.00 mb/sec
3846.15 mb/sec
4000.00 mb/sec
4000.00 mb/sec
4000.00 mb/sec
```

Before max was about 3750 mb/s

If you use references, instead of local variables it increases the performance even more.

But before we optimize it, we should integrate it. 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@kibertoad  that was the plan :)

This one has just replaced the old buffer construction calls to Buffer.from and Buffer.allocate. I also added the license to the head of the file.

**Comment by kibertoad** [comment]
Would be better to move buffer changes and unit tests into separate PR as well, otherwise it will be very difficult to track down how and when that was changed later :)

**Comment by kibertoad** [comment]
If you want, I can create PR doing just pure integration, and you can drop this PR on top of it. Does that work for you?

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
Good point on not squashing, that is perfectly sufficient.

**Comment by kibertoad** [comment]
@Uzlopak BTW, can you create a PR adding yourself into Contributors section in https://github.com/fastify/busboy/blob/master/package.json?

**Pull request merged**
