### PR TITLE
perf: refactor parts of StreamSearch

### PR DESCRIPTION
**Pull request by gurgunday**
Goal: Modernize and improve this library as much possible starting with StreamSearch

Small improvements:

https://github.com/fastify/busboy/commit/a4e91c508f61dc45f8507e689280e51380a67317 — when we match, no need to calculate the pos again, let's just directly assign and check
https://github.com/fastify/busboy/commit/c281addf88a4f701af71f28d309fe802a8b23a70 — unnecessary allocation
https://github.com/fastify/busboy/commit/ca4602dc1f93ebb130b24ccdc92590b13eaffc01 — unnecessary subtraction

### CODE REVIEW

**Comment by gurgunday** [comment]
@Uzlopak should I separate the code changes that are attached in the description from the class refactor?

**Comment by gurgunday** [comment]
I will separate the changes in different PRs

**Comment by gurgunday** [comment]
This is a minor change, so that the bigger refactor doesn't introduce any other changes

**Review by Uzlopak — APPROVED** [review]
Makes sense

**Pull request merged**
